// Copyright (c) 2025 Inan Evin

#pragma once

namespace SFG
{
#define MAX_ENTITIES				   16000
#define MAX_WORLD_RESOURCES_AUX_MEMORY 1024 * 1024 * 4
#define MAX_WORLD_TRAITS_AUX_MEMORY	   1024 * 512

#define MAX_WORLD_MODEL_INSTANCES	 1024
#define MAX_WORLD_TEXTURES			 32
#define MAX_WORLD_MODELS			 32
#define MAX_WORLD_MESHES			 256
#define MAX_WORLD_ANIMS				 32
#define MAX_WORLD_SKINS				 12
#define MAX_WORLD_MATERIALS			 20
#define MAX_WORLD_SHADERS			 30
#define MAX_WORLD_AUDIO				 50
#define MAX_WORLD_FONTS				 20
#define MAX_WORLD_PHYSICAL_MATERIALS 30
#define MAX_WORLD_SAMPLERS			 16

#define MAX_WORLD_TRAIT_CAMERAS			 32
#define MAX_WORLD_TRAIT_DIR_LIGHTS		 8
#define MAX_WORLD_TRAIT_POINT_LIGHTS	 128
#define MAX_WORLD_TRAIT_SPOT_LIGHTS		 128
#define MAX_WORLD_TRAIT_MESH_INSTANCES	 1024 * 10
#define MAX_WORLD_TRAIT_MODEL_INSTANCES 1024
}
